name: Build/release

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                arch: [x86, arm64]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install Ubuntu X11
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install libx11-dev libxext-dev libxtst-dev libxrender-dev libxmu-dev libxmuu-dev

            - name: set arm64 on win
              if: matrix.arch == 'arm64' && matrix.os == 'windows-latest'
              run: |
                  set npm_config_arch=arm64
            - name: set arm64 on mac
              if: matrix.arch == 'arm64' && matrix.os == 'macos-latest'
              run: |
                  export npm_config_arch=arm64
            - name: ${{ matrix.os }} ${{ matrix.arch }} build
              run: |
                  npm install
                  npm run dist

            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  path: |
                      build/*.exe
                      build/*.zip
                      build/*.tar.gz
                      build/*.deb
                      build/*.rpm
                      build/*.dmg

            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: "build/*"
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
